### PR TITLE
Ability to specify reference directory.

### PR DESCRIPTION
**Pull request by ElliottLandsborough**
This can speed up pulls of large remote repositories.

More info here: http://randyfay.com/content/reference-cache-repositories-speed-clones-git-clone-reference

### CODE REVIEW

**Comment by kbjr** [comment]
Why did the `$repo->log` function get killed?

**Comment by ElliottLandsborough** [comment]
Hah. Okay that looks like lack of sleep on my part.

I will submit a new patch when I get home.

**Comment by kbjr** [comment]
Can you squash these commits please? Then I will merge it in. Thanks.

**Comment by ElliottLandsborough** [comment]
All done.

**Pull request closed without merging**
