### PR TITLE
Refactor to PSR-4

### PR DESCRIPTION
**Pull request by adrorocker**
This PR refactor the code:

- To be in compliance with [PSR-4](https://www.php-fig.org/psr/psr-4/)
- To be in compliance with [PSR-1](https://www.php-fig.org/psr/psr-1/) at least.
- Prepare to, hopefully, publish this code in [packagist.org](https://packagist.org/)

### CODE REVIEW

**Comment by kbjr** [comment]
I've been out of the world of PHP for _a while_ now, so I'm kind of learning how to.. read again. But this mostly all looks like pretty straight-forward good stuff, and I'm inclined to pull it in.

You mentioned hoping to get the library published, is there anything more that you need beyond these changes to make that happen?

**Comment by adrorocker** [comment]
@kbjr Thanks for considering my PR. Well, I want to use this in one of my projects and I would like to add it with composer, there needs to be some configuration in the repo and packagist.com in order to accomplish this. If you like I could take care of this is you give me temporary access to the configuration of this repo and collaboration access.

Also I notice you *had* a `gh-pages` branch to host the documentation. Now you can just have the same "main" branch to serve the `docs` directory in https://kbjr.github.io/Git.php/ I was about to update the repo with that too but not sure what you were using to generate it. I can take care of that too if you like.

**Comment by adrorocker** [comment]
Hey there @kbjr, is there anything I can do to help on this? or have you decided not to merge it?

Thanks in advance.

**Comment by kbjr** [comment]
That docs page was old / outdated. If you would like to create new docs, I would be perfectly happy to pull those in as well.

**Pull request merged**
